name: Windows x64

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup .NET Core 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Build solution
        run: dotnet build -c Release --verbosity minimal

      - name: Run tests
        run: dotnet test -c Release --verbosity normal --no-build --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-build --no-restore