name: Ubuntu x64

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3

      - name: Setup .NET Core 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          
      - name: Build solution
        run: dotnet build -c Release --verbosity minimal

      - name: Run tests
        run: dotnet test -c Release --verbosity normal --no-build --no-restore

      - name: Publish
        run: dotnet publish -c Release --no-build --no-restore