name: Ubuntu x64

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Linux   # Set your environment here (e.g., 'production', 'staging', etc.)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build solution
        run: dotnet build -c Release ./src --verbosity minimal

      - name: Run tests and collect coverage
        run: |
          dotnet test -c Release ./src --verbosity normal --no-build --no-restore \
          --collect:"XPlat Code Coverage" --results-directory ./TestResults/ \
          /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura \
          /p:CoverletOutput=./TestResults/coverage.cobertura.xml

      - name: List files in TestResults directory
        run: ls -R ./TestResults

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./TestResults/**/coverage.cobertura.xml
          flags: unit
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true
